---
- name: Provisioning SFTP Server Image
  hosts: all
  become: yes
  become_user: root
  vars:
    
    - sftp_users:
      - name: peter
        password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass
        shell: False
        sftp_directories:
        - directory_only_for_peter1
        - directory_only_for_peter2
      - name: sally
        password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass
        shell: True
        home: /var/tmp/sally
        append: True
    - sftp_directories:
      - imports
      - exports
      - { name: public, mode: 755 }
      - other

    - ansible_python_interpreter: /usr/bin/python3

  roles:
    - { role: sftp-server, tags: sftp }